import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROMPTS_ROOT = ROOT / "prompts"


class RunDocsContractTests(unittest.TestCase):
    def test_run_spec_mentions_dynamic_gate_expansion(self):
        text = (ROOT / "run.md").read_text(encoding="utf-8")
        self.assertIn("RUNNER_DONE.lock", text)
        self.assertIn("/prompts:run_execute", text)
        self.assertIn("/prompts:run_govern", text)
        self.assertIn("/prompts:run_setup", text)
        self.assertIn("OBJECTIVE.json", text)
        self.assertIn("SEAMS.json", text)
        self.assertIn("GAPS.json", text)
        self.assertIn("RUNNER_CYCLE_PREPARED.json", text)
        self.assertIn("RUNNER_HANDOFF.md", text)
        self.assertIn("RUNNER_ACTIVE_BACKLOG.json", text)
        self.assertIn("RUNNER_PARITY.json", text)
        self.assertIn("RUNNER_GRAPH_ACTIVE_SLICE.json", text)
        self.assertIn("RUNNER_DEP_GRAPH.json", text)
        self.assertIn(".memory/PRD.md", text)
        self.assertIn("controller dispatches `/prompts:run_execute ...` first", text)
        self.assertIn("controller scripts deterministic refresh itself with `runctl --setup` and `runctl --prepare-cycle`", text)
        self.assertIn("when execute reports `needs_update=yes`, controller dispatches `/prompts:run_govern ...` in the same Codex session when that session already matches the requested update profile; otherwise it relaunches a fresh session for the required profile", text)
        self.assertIn("when scripted refresh fails to produce the prepared marker, controller likewise prefers same-session `/prompts:run_govern ...` to preserve execute context and only relaunches when the update profile is incompatible with the current session", text)
        self.assertIn("after govern, controller again scripts deterministic refresh itself with `runctl --setup` and `runctl --prepare-cycle`", text)
        self.assertIn("supervisor archives completed runner threads itself between cycles", text)
        self.assertIn("resolve the active seam profile at the start of each cycle", text)
        self.assertIn("model_profile=mini", text)
        self.assertIn("`/prompts:run_setup` is for human reset/rebuild only.", text)
        self.assertIn("run `/prompts:run_govern`", text)
        self.assertIn("prefer the smallest truthful recovery", text)
        self.assertIn("treat coupling as a split trigger", text)
        self.assertIn("synthesize or reopen one final done-closeout seam instead of inferring completion", text)
        self.assertIn("only write `.memory/runner/locks/RUNNER_DONE.lock` after that explicit done-closeout seam passes `run_gates`", text)
        self.assertIn("the infinite runner should keep healing through seam repair, validation repair, and explicit closeout until completion is both semantically and operationally safe", text)
        self.assertIn("if a `mini` `run_govern` still cannot produce the prepared marker, controller retries `run_govern` on `high`", text)
        self.assertIn("controller queues a high-priority recovery triage task", text)
        self.assertIn("run_setup.md", text)
        self.assertIn("run_execute.md", text)
        self.assertIn("run_govern.md", text)
        self.assertIn("graph generation is controller/script-owned and opt-in per repo", text)
        self.assertIn("one-open actionable frontier", text)
        self.assertIn("graph_slice_reason", text)
        self.assertIn("creates fresh runner state and a deliberately narrow backlog", text)
        self.assertIn("seeded tasks should be concise and decoupled", text)

    def test_run_setup_prompt_exists_and_clears_then_sets_up(self):
        text = (PROMPTS_ROOT / "run_setup.md").read_text(encoding="utf-8")
        self.assertIn("This is the human reset/rebuild path.", text)
        self.assertIn("This prompt is for the user/human setup flow only.", text)
        self.assertIn("runctl --clear", text)
        self.assertIn("confirm_token", text)
        self.assertIn("skip clear and run only", text)
        self.assertIn("Objective Seeding", text)
        self.assertIn("generic, or stale", text)
        self.assertIn("never seed a boilerplate generic `TT-001`", text)
        self.assertIn("PRD.json", text)
        self.assertIn("OBJECTIVE.json", text)
        self.assertIn("SEAMS.json", text)
        self.assertIn("GAPS.json", text)
        self.assertIn("TASKS.json", text)
        self.assertIn("Use the latest explicit user goal as the source of truth.", text)
        self.assertIn("current repo state, not just stored memory", text)
        self.assertIn("git status --short", text)
        self.assertIn("current dirty worktree concentration", text)
        self.assertIn("prefer active backlog only", text)
        self.assertIn("concise task text that names the first file family", text)
        self.assertIn("For every seeded task:", text)
        self.assertIn("if the human is rerunning setup after a stalled runner, do not reseed the same broad task unchanged", text)
        self.assertIn("use the smallest regrouping needed to restore momentum", text)
        self.assertIn("preserve a healthy task unchanged when its family boundary is still correct", text)
        self.assertIn("do not seed one task across multiple dominant dependency clusters", text)
        self.assertIn("if the request clearly contains multiple independent deliverables", text)
        self.assertIn("set `model_profile` to `mini` or `high`", text)
        self.assertIn("include `touch_paths`", text)
        self.assertIn("include `coupling_notes`", text)
        self.assertIn("safe deprecation order", text)
        self.assertIn("order setup decisions explicitly", text)
        self.assertIn("fix the dependency chain", text)
        self.assertIn("fix sequencing by safe deprecation phase", text)
        self.assertIn("choose the lowest-complexity slice that still has a real chance of completion in one cycle", text)
        self.assertIn("leave exactly one actionable `open` task when one next step is obvious", text)
        self.assertIn("`high` is not permission for a broad umbrella task", text)
        self.assertIn("if graph artifacts exist under `.memory/runner/graph/`, use them as the first structural hint", text)
        self.assertIn("RUNNER_DEP_GRAPH.json", text)
        self.assertIn("RUNNER_GRAPH_BOUNDARIES.json", text)
        self.assertIn("RUNNER_GRAPH_HOTSPOTS.json", text)
        self.assertIn("derive `touch_paths`, `spillover_paths`, `coupling_notes`, and `fanout_risk` from actual dependency neighborhoods", text)
        self.assertIn("useAppLayoutStore*` plus `useAppStore*", text)
        self.assertIn("make acceptance fail-closed", text)
        self.assertIn("Task seeding must be narrow enough for a single runner slice:", text)
        self.assertIn("Do not seed broad task titles such as:", text)
        self.assertIn("seed acceptance as fail-closed, not approximate", text)
        self.assertIn("record the exact baseline commit or artifact", text)
        self.assertIn("resolve one explicit safe baseline commit", text)
        self.assertIn("RUNNER_PARITY.json", text)
        self.assertIn("parity_surface_ids", text)
        self.assertIn("Playwright MCP", text)
        self.assertIn("Tauri MCP", text)
        self.assertIn("git diff", text)
        self.assertIn("For subjective polish or UX work that is not baseline matching:", text)
        self.assertIn("seeded first task title if relevant", text)
        self.assertIn("Do not use this prompt as the infinite runner's automatic recovery step", text)
        self.assertIn("runctl --setup", text)
        self.assertIn("RUNNER_STATE.json", text)
        self.assertIn("TASKS.json", text)
        self.assertIn("Do not start the runner from this prompt.", text)

    def test_run_execute_prompt_exists_and_is_execute_only(self):
        text = (PROMPTS_ROOT / "run_execute.md").read_text(encoding="utf-8")
        self.assertIn("OBJECTIVE.json", text)
        self.assertIn("SEAMS.json", text)
        self.assertIn("GAPS.json", text)
        self.assertIn("RUNNER_EXEC_CONTEXT.json", text)
        self.assertIn("RUNNER_ACTIVE_BACKLOG.json", text)
        self.assertIn("RUNNER_GRAPH_ACTIVE_SLICE.json", text)
        self.assertIn("medium bounded infinite-runner work slice", text)
        self.assertIn("The runner controller will script deterministic refresh itself after this prompt completes.", text)
        self.assertIn("It will invoke `/prompts:run_govern` in the same Codex session", text)
        self.assertIn("treat the current active seam as the stable unit of ownership", text)
        self.assertIn("Use the active seam metadata in `RUNNER_EXEC_CONTEXT.json` as hard scope", text)
        self.assertIn("Treat `RUNNER_HANDOFF.md` as human/manual recovery context", text)
        self.assertIn("Do not load `RUNNER_DEP_GRAPH.json`, `RUNNER_GRAPH_BOUNDARIES.json`, or `RUNNER_GRAPH_HOTSPOTS.json` during normal execute.", text)
        self.assertIn("graph_boundary_warnings_top3", text)
        self.assertIn("graph_slice_reason", text)
        self.assertIn("graph_adjacent_families_top3", text)
        self.assertIn("do not widen beyond `touch_paths`", text)
        self.assertIn("`coupling_notes`", text)
        self.assertIn("if the repo already has unrelated dirty files outside `touch_paths`", text)
        self.assertIn("slice turns out to depend on a partially migrated adjacent family", text)
        self.assertIn("second independent family would be a scope failure", text)
        self.assertIn("keep the active seam open until its acceptance criteria are actually satisfied", text)
        self.assertIn("stay on the same active seam across cycles by default", text)
        self.assertIn("if the current seam is actually complete, say so explicitly in the structured runner update", text)
        self.assertIn("include its canonical seam id in the structured runner update", text)
        self.assertIn("the objective is only complete after the explicit done-closeout seam passes final `run_gates`", text)
        self.assertIn("if new in-scope acceptance criteria are discovered", text)
        self.assertIn("do not move to a different seam while the current seam's acceptance is still unmet", text)
        self.assertIn("Any problems with the current implementation?", text)
        self.assertIn("name every real remaining issue", text)
        self.assertIn("treat that as fail-closed", text)
        self.assertIn("do not use `phase_done=yes` for a parity-style seam", text)
        self.assertIn("parity_baseline_ref", text)
        self.assertIn("parity_surface_ids", text)
        self.assertIn("parity_surfaces", text)
        self.assertIn("parity_harness_commands", text)
        self.assertIn("use the recorded baseline commit in `parity_baseline_ref` as the first comparison point", text)
        self.assertIn("do not run broad parity audits every cycle", text)
        self.assertIn("inspect the DOM or component tree only for the affected surfaces", text)
        self.assertIn("for subjective polish or UX seams, require direct evidence", text)
        self.assertIn("phase_done=<yes|no>", text)
        self.assertIn("needs_update=<yes|no>", text)
        self.assertIn("scope_status=<ok|narrow|split|reseed>", text)
        self.assertIn("do not overuse `scope_status=reseed`", text)
        self.assertIn("prefer `narrow` over `split`, and `split` over `reseed`", text)
        self.assertIn("if implementation starts pulling in files named in `spillover_paths`", text)
        self.assertIn("if `RUNNER_GRAPH_ACTIVE_SLICE.json` shows a direct boundary crossing into an adjacent family", text)
        self.assertIn("treat `graph_slice_reason` as the compact rationale for why this frontier is open", text)
        self.assertIn("scripted refresh cannot produce the prepared marker", text)
        self.assertIn("update_profile=<mini|high>", text)

    def test_run_govern_prompt_exists_and_is_update_only(self):
        text = (PROMPTS_ROOT / "run_govern.md").read_text(encoding="utf-8")
        self.assertIn("autonomous seam-governor prompt", text)
        self.assertIn("OBJECTIVE.json", text)
        self.assertIn("SEAMS.json", text)
        self.assertIn("GAPS.json", text)
        self.assertIn("decision=<continue_seam|complete_seam|split_seam|create_prereq_seam|defer_gaps_and_continue|objective_complete|halt>", text)

    def test_add_prompt_exists_and_queues_runner_task_intake(self):
        text = (PROMPTS_ROOT / "add.md").read_text(encoding="utf-8")
        self.assertIn("runctl --task add", text)
        self.assertIn("runctl --task set", text)
        self.assertIn("RUNNER_STATE.json", text)
        self.assertIn("TASKS.json", text)
        self.assertIn("If the human gives a repo path ending in `.memory`", text)
        self.assertIn("/Users/jian/Dev/Repos/time-track/.memory", text)
        self.assertIn("If the request is short or underspecified, combine it with the active conversation context", text)
        self.assertIn("Treat the current conversation as the default repo signal", text)
        self.assertIn(".memory/PRD.md", text)
        self.assertIn(".memory/lessons.md", text)
        self.assertIn("Existing Task Triage", text)
        self.assertIn("RUNNER_TASK_INTAKE.json", text)
        self.assertIn("Do not create or refresh runner setup from `/add`.", text)
        self.assertIn("`--allow-preempt` only if the human explicitly asks", text)
        self.assertIn("If more than one plausible runner root exists, ask the human", text)
        self.assertIn("/prompts:run_setup", text)

    def test_legacy_phase_prompts_are_not_required_in_default_install(self):
        for prompt_name in ("run.md", "run_clear.md", "runner-cycle.md", "runner-discover.md", "runner-implement.md", "runner-verify.md", "runner-closeout.md"):
            self.assertFalse((PROMPTS_ROOT / prompt_name).exists())

    def test_install_script_links_add_prompt(self):
        text = (ROOT / "scripts" / "install-codex-run-prompt.sh").read_text(encoding="utf-8")
        self.assertIn('SOURCE_DIR="$REPO_HOME/prompts"', text)
        self.assertIn("for prompt_name in run_setup run_execute run_govern add", text)
        self.assertIn("for legacy_prompt in run run_clear runner-cycle runner-discover runner-implement runner-verify runner-closeout", text)
        self.assertIn("ln -s", text)


if __name__ == "__main__":
    unittest.main()
